### ISSUE TITLE
Please add english tutorial

### ISSUE THREAD

**Issue by Tucumanos** [Paranoid-AF/Ecco#1]
> Astounding work, I'm thinking in implementing in my server if everything works fine.

**Comment by Paranoid-AF** [comment]
First off, thank you for your attention.
I didn't expect this project to be seen by other people in the first place, so I just wrote the wiki in Chinese to get my friends into it.
Now that you've discovered this repo...well, I will translate the wiki as soon as I have a bunch of free time, since that's time-consuming and boring somehow. And before that, I need to update the original wiki, due to some change to the code.
Stay tuned, it can be a long wait tho.

**Comment by Tucumanos** [comment]
Yay, no problem I can wait, thanks!
